// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
	properties: {
		grant_type: {
			anyOf: [
				{
					type: 'string',
					pattern: '^password$',
				},
				{
					type: 'null',
				},
			],
			title: 'Grant Type',
		},
		username: {
			type: 'string',
			title: 'Username',
		},
		password: {
			type: 'string',
			format: 'password',
			title: 'Password',
		},
		scope: {
			type: 'string',
			title: 'Scope',
			default: '',
		},
		client_id: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Client Id',
		},
		client_secret: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			format: 'password',
			title: 'Client Secret',
		},
	},
	type: 'object',
	required: ['username', 'password'],
	title: 'Body_login-login_access_token',
} as const;

export const CensusDataSchema = {
	properties: {
		academic_year: {
			type: 'integer',
			title: 'Academic Year',
		},
		aggregation_level: {
			type: 'string',
			title: 'Aggregation Level',
		},
		county_code: {
			type: 'string',
			title: 'County Code',
		},
		district_code: {
			type: 'string',
			title: 'District Code',
		},
		school_code: {
			type: 'string',
			title: 'School Code',
		},
		county_name: {
			type: 'string',
			maxLength: 255,
			title: 'County Name',
		},
		district_name: {
			type: 'string',
			maxLength: 255,
			title: 'District Name',
		},
		school_name: {
			type: 'string',
			maxLength: 255,
			title: 'School Name',
		},
		charter: {
			type: 'string',
			maxLength: 255,
			title: 'Charter',
		},
		reporting_category: {
			type: 'string',
			maxLength: 255,
			title: 'Reporting Category',
		},
		total_enr: {
			type: 'integer',
			title: 'Total Enr',
			default: 0,
		},
		gr_tk: {
			type: 'integer',
			title: 'Gr Tk',
			default: 0,
		},
		gr_kn: {
			type: 'integer',
			title: 'Gr Kn',
			default: 0,
		},
		gr_1: {
			type: 'integer',
			title: 'Gr 1',
			default: 0,
		},
		gr_2: {
			type: 'integer',
			title: 'Gr 2',
			default: 0,
		},
		gr_3: {
			type: 'integer',
			title: 'Gr 3',
			default: 0,
		},
		gr_4: {
			type: 'integer',
			title: 'Gr 4',
			default: 0,
		},
		gr_5: {
			type: 'integer',
			title: 'Gr 5',
			default: 0,
		},
		gr_6: {
			type: 'integer',
			title: 'Gr 6',
			default: 0,
		},
		gr_7: {
			type: 'integer',
			title: 'Gr 7',
			default: 0,
		},
		gr_8: {
			type: 'integer',
			title: 'Gr 8',
			default: 0,
		},
		gr_9: {
			type: 'integer',
			title: 'Gr 9',
			default: 0,
		},
		gr_10: {
			type: 'integer',
			title: 'Gr 10',
			default: 0,
		},
		gr_11: {
			type: 'integer',
			title: 'Gr 11',
			default: 0,
		},
		gr_12: {
			type: 'integer',
			title: 'Gr 12',
			default: 0,
		},
		census_data_id: {
			type: 'string',
			format: 'uuid',
			title: 'Census Data Id',
		},
	},
	type: 'object',
	required: [
		'academic_year',
		'aggregation_level',
		'county_code',
		'district_code',
		'school_code',
		'county_name',
		'district_name',
		'school_name',
		'charter',
		'reporting_category',
	],
	title: 'CensusData',
} as const;

export const HTTPValidationErrorSchema = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError',
			},
			type: 'array',
			title: 'Detail',
		},
	},
	type: 'object',
	title: 'HTTPValidationError',
} as const;

export const ItemCreateSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	required: ['title'],
	title: 'ItemCreate',
} as const;

export const ItemPublicSchema = {
	properties: {
		title: {
			type: 'string',
			maxLength: 255,
			minLength: 1,
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		owner_id: {
			type: 'string',
			format: 'uuid',
			title: 'Owner Id',
		},
	},
	type: 'object',
	required: ['title', 'id', 'owner_id'],
	title: 'ItemPublic',
} as const;

export const ItemUpdateSchema = {
	properties: {
		title: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					minLength: 1,
				},
				{
					type: 'null',
				},
			],
			title: 'Title',
		},
		description: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Description',
		},
	},
	type: 'object',
	title: 'ItemUpdate',
} as const;

export const ItemsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/ItemPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'ItemsPublic',
} as const;

export const MessageSchema = {
	properties: {
		message: {
			type: 'string',
			title: 'Message',
		},
	},
	type: 'object',
	required: ['message'],
	title: 'Message',
} as const;

export const NewPasswordSchema = {
	properties: {
		token: {
			type: 'string',
			title: 'Token',
		},
		new_password: {
			type: 'string',
			maxLength: 40,
			minLength: 8,
			title: 'New Password',
		},
	},
	type: 'object',
	required: ['token', 'new_password'],
	title: 'NewPassword',
} as const;

export const PrivateUserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			title: 'Email',
		},
		password: {
			type: 'string',
			title: 'Password',
		},
		full_name: {
			type: 'string',
			title: 'Full Name',
		},
		is_verified: {
			type: 'boolean',
			title: 'Is Verified',
			default: false,
		},
	},
	type: 'object',
	required: ['email', 'password', 'full_name'],
	title: 'PrivateUserCreate',
} as const;

export const SchoolPublicSchema = {
	properties: {
		cds_code: {
			type: 'string',
			maxLength: 255,
			title: 'Cds Code',
		},
		nces_dist: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Nces Dist',
		},
		nces_school: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Nces School',
		},
		status_type: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Status Type',
		},
		county: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'County',
		},
		district: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'District',
		},
		school: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'School',
		},
		street: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Street',
		},
		street_abr: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Street Abr',
		},
		city: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'City',
		},
		zip: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Zip',
		},
		state: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'State',
		},
		mail_street: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Mail Street',
		},
		mail_street_abr: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Mail Street Abr',
		},
		mail_city: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mail City',
		},
		mail_zip: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mail Zip',
		},
		mail_state: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Mail State',
		},
		phone: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Phone',
		},
		ext: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Ext',
		},
		fax_number: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Fax Number',
		},
		website: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Website',
		},
		open_date: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Open Date',
		},
		closed_date: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Closed Date',
		},
		charter: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter',
		},
		charter_num: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Charter Num',
		},
		funding_type: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Funding Type',
		},
		doc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Doc',
		},
		doc_type: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Doc Type',
		},
		soc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Soc',
		},
		soc_type: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Soc Type',
		},
		edops_code: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Edops Code',
		},
		edops_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Edops Name',
		},
		eil_code: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Eil Code',
		},
		eil_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Eil Name',
		},
		gs_offered: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Gs Offered',
		},
		gs_served: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Gs Served',
		},
		virtual: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Virtual',
		},
		magnet: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Magnet',
		},
		year_round_yn: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Year Round Yn',
		},
		federal_dfc_district_id: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Federal Dfc District Id',
		},
		latitude: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Latitude',
		},
		longitude: {
			anyOf: [
				{
					type: 'number',
				},
				{
					type: 'null',
				},
			],
			title: 'Longitude',
		},
		adm_fname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Adm Fname',
		},
		adm_lname: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Adm Lname',
		},
		last_up_date: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Last Up Date',
		},
		multilingual: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Multilingual',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
	},
	type: 'object',
	required: ['cds_code', 'id'],
	title: 'SchoolPublic',
} as const;

export const SchoolSummarySchema = {
	properties: {
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
		school: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'School',
		},
		city: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'City',
		},
		county: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'County',
		},
		cds_code: {
			anyOf: [
				{
					type: 'string',
				},
				{
					type: 'null',
				},
			],
			title: 'Cds Code',
		},
	},
	type: 'object',
	required: ['id'],
	title: 'SchoolSummary',
} as const;

export const SchoolsPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/SchoolPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'SchoolsPublic',
} as const;

export const SchoolsSummarySchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/SchoolSummary',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'SchoolsSummary',
} as const;

export const TokenSchema = {
	properties: {
		access_token: {
			type: 'string',
			title: 'Access Token',
		},
		token_type: {
			type: 'string',
			title: 'Token Type',
			default: 'bearer',
		},
	},
	type: 'object',
	required: ['access_token'],
	title: 'Token',
} as const;

export const UpdatePasswordSchema = {
	properties: {
		current_password: {
			type: 'string',
			maxLength: 40,
			minLength: 8,
			title: 'Current Password',
		},
		new_password: {
			type: 'string',
			maxLength: 40,
			minLength: 8,
			title: 'New Password',
		},
	},
	type: 'object',
	required: ['current_password', 'new_password'],
	title: 'UpdatePassword',
} as const;

export const UserCreateSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		is_active: {
			type: 'boolean',
			title: 'Is Active',
			default: true,
		},
		is_superuser: {
			type: 'boolean',
			title: 'Is Superuser',
			default: false,
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		password: {
			type: 'string',
			maxLength: 40,
			minLength: 8,
			title: 'Password',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserCreate',
} as const;

export const UserPublicSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		is_active: {
			type: 'boolean',
			title: 'Is Active',
			default: true,
		},
		is_superuser: {
			type: 'boolean',
			title: 'Is Superuser',
			default: false,
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		id: {
			type: 'string',
			format: 'uuid',
			title: 'Id',
		},
	},
	type: 'object',
	required: ['email', 'id'],
	title: 'UserPublic',
} as const;

export const UserRegisterSchema = {
	properties: {
		email: {
			type: 'string',
			maxLength: 255,
			format: 'email',
			title: 'Email',
		},
		password: {
			type: 'string',
			maxLength: 40,
			minLength: 8,
			title: 'Password',
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
	},
	type: 'object',
	required: ['email', 'password'],
	title: 'UserRegister',
} as const;

export const UserUpdateSchema = {
	properties: {
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
		is_active: {
			type: 'boolean',
			title: 'Is Active',
			default: true,
		},
		is_superuser: {
			type: 'boolean',
			title: 'Is Superuser',
			default: false,
		},
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		password: {
			anyOf: [
				{
					type: 'string',
					maxLength: 40,
					minLength: 8,
				},
				{
					type: 'null',
				},
			],
			title: 'Password',
		},
	},
	type: 'object',
	title: 'UserUpdate',
} as const;

export const UserUpdateMeSchema = {
	properties: {
		full_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
				},
				{
					type: 'null',
				},
			],
			title: 'Full Name',
		},
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255,
					format: 'email',
				},
				{
					type: 'null',
				},
			],
			title: 'Email',
		},
	},
	type: 'object',
	title: 'UserUpdateMe',
} as const;

export const UsersPublicSchema = {
	properties: {
		data: {
			items: {
				$ref: '#/components/schemas/UserPublic',
			},
			type: 'array',
			title: 'Data',
		},
		count: {
			type: 'integer',
			title: 'Count',
		},
	},
	type: 'object',
	required: ['data', 'count'],
	title: 'UsersPublic',
} as const;

export const ValidationErrorSchema = {
	properties: {
		loc: {
			items: {
				anyOf: [
					{
						type: 'string',
					},
					{
						type: 'integer',
					},
				],
			},
			type: 'array',
			title: 'Location',
		},
		msg: {
			type: 'string',
			title: 'Message',
		},
		type: {
			type: 'string',
			title: 'Error Type',
		},
	},
	type: 'object',
	required: ['loc', 'msg', 'type'],
	title: 'ValidationError',
} as const;
