// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
};

export type CensusData = {
	academic_year: number;
	aggregation_level: string;
	county_code: string;
	district_code: string;
	school_code: string;
	county_name: string;
	district_name: string;
	school_name: string;
	charter: string;
	reporting_category: string;
	total_enr?: number;
	gr_tk?: number;
	gr_kn?: number;
	gr_1?: number;
	gr_2?: number;
	gr_3?: number;
	gr_4?: number;
	gr_5?: number;
	gr_6?: number;
	gr_7?: number;
	gr_8?: number;
	gr_9?: number;
	gr_10?: number;
	gr_11?: number;
	gr_12?: number;
	census_data_id?: string;
};

export type HTTPValidationError = {
	detail?: Array<ValidationError>;
};

export type ItemCreate = {
	title: string;
	description?: string | null;
};

export type ItemPublic = {
	title: string;
	description?: string | null;
	id: string;
	owner_id: string;
};

export type ItemsPublic = {
	data: Array<ItemPublic>;
	count: number;
};

export type ItemUpdate = {
	title?: string | null;
	description?: string | null;
};

export type Message = {
	message: string;
};

export type NewPassword = {
	token: string;
	new_password: string;
};

export type PrivateUserCreate = {
	email: string;
	password: string;
	full_name: string;
	is_verified?: boolean;
};

export type SchoolPublic = {
	cds_code: string;
	nces_dist?: string | null;
	nces_school?: string | null;
	status_type?: string | null;
	county?: string | null;
	district?: string | null;
	school?: string | null;
	street?: string | null;
	street_abr?: string | null;
	city?: string | null;
	zip?: string | null;
	state?: string | null;
	mail_street?: string | null;
	mail_street_abr?: string | null;
	mail_city?: string | null;
	mail_zip?: string | null;
	mail_state?: string | null;
	phone?: string | null;
	ext?: string | null;
	fax_number?: string | null;
	website?: string | null;
	open_date?: string | null;
	closed_date?: string | null;
	charter?: string | null;
	charter_num?: string | null;
	funding_type?: string | null;
	doc?: string | null;
	doc_type?: string | null;
	soc?: string | null;
	soc_type?: string | null;
	edops_code?: string | null;
	edops_name?: string | null;
	eil_code?: string | null;
	eil_name?: string | null;
	gs_offered?: string | null;
	gs_served?: string | null;
	virtual?: string | null;
	magnet?: string | null;
	year_round_yn?: string | null;
	federal_dfc_district_id?: string | null;
	latitude?: number | null;
	longitude?: number | null;
	adm_fname?: string | null;
	adm_lname?: string | null;
	last_up_date?: string | null;
	multilingual?: string | null;
	id: string;
};

export type SchoolsPublic = {
	data: Array<SchoolPublic>;
	count: number;
};

export type SchoolsSummary = {
	data: Array<SchoolSummary>;
	count: number;
};

export type SchoolSummary = {
	id: string;
	school?: string | null;
	city?: string | null;
	county?: string | null;
	cds_code?: string | null;
};

export type Token = {
	access_token: string;
	token_type?: string;
};

export type UpdatePassword = {
	current_password: string;
	new_password: string;
};

export type UserCreate = {
	email: string;
	is_active?: boolean;
	is_superuser?: boolean;
	full_name?: string | null;
	password: string;
};

export type UserPublic = {
	email: string;
	is_active?: boolean;
	is_superuser?: boolean;
	full_name?: string | null;
	id: string;
};

export type UserRegister = {
	email: string;
	password: string;
	full_name?: string | null;
};

export type UsersPublic = {
	data: Array<UserPublic>;
	count: number;
};

export type UserUpdate = {
	email?: string | null;
	is_active?: boolean;
	is_superuser?: boolean;
	full_name?: string | null;
	password?: string | null;
};

export type UserUpdateMe = {
	full_name?: string | null;
	email?: string | null;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type CensusdataCountOfCensusDataData = {
	limit?: number;
	skip?: number;
};

export type CensusdataCountOfCensusDataResponse = Array<CensusData>;

export type CensusdataCreateCensusDataData = {
	requestBody: CensusData;
};

export type CensusdataCreateCensusDataResponse = CensusData;

export type CensusdataReadCensusDataData = {
	id: string;
};

export type CensusdataReadCensusDataResponse = CensusData;

export type CensusdataUpdateCensusDataData = {
	id: string;
	requestBody: CensusData;
};

export type CensusdataUpdateCensusDataResponse = CensusData;

export type CensusdataDeleteCensusDataData = {
	id: string;
};

export type CensusdataDeleteCensusDataResponse = CensusData;

export type ItemsReadItemsData = {
	limit?: number;
	skip?: number;
};

export type ItemsReadItemsResponse = ItemsPublic;

export type ItemsCreateItemData = {
	requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = ItemPublic;

export type ItemsReadItemData = {
	id: string;
};

export type ItemsReadItemResponse = ItemPublic;

export type ItemsUpdateItemData = {
	id: string;
	requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = ItemPublic;

export type ItemsDeleteItemData = {
	id: string;
};

export type ItemsDeleteItemResponse = Message;

export type LoginLoginAccessTokenData = {
	formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type LoginRecoverPasswordData = {
	email: string;
};

export type LoginRecoverPasswordResponse = Message;

export type LoginResetPasswordData = {
	requestBody: NewPassword;
};

export type LoginResetPasswordResponse = Message;

export type LoginRecoverPasswordHtmlContentData = {
	email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = string;

export type PrivateCreateUserData = {
	requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = UserPublic;

export type SchoolsReadSchoolsData = {
	limit?: number;
	q?: string | null;
	skip?: number;
};

export type SchoolsReadSchoolsResponse = SchoolsPublic;

export type SchoolsReadSchoolsSummaryData = {
	limit?: number;
	q?: string | null;
	skip?: number;
};

export type SchoolsReadSchoolsSummaryResponse = SchoolsSummary;

export type UsersReadUsersData = {
	limit?: number;
	skip?: number;
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersCreateUserData = {
	requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersDeleteUserMeResponse = Message;

export type UsersUpdateUserMeData = {
	requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = UserPublic;

export type UsersUpdatePasswordMeData = {
	requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = Message;

export type UsersRegisterUserData = {
	requestBody: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersReadUserByIdData = {
	userId: string;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersUpdateUserData = {
	requestBody: UserUpdate;
	userId: string;
};

export type UsersUpdateUserResponse = UserPublic;

export type UsersDeleteUserData = {
	userId: string;
};

export type UsersDeleteUserResponse = Message;

export type UtilsTestEmailData = {
	emailTo: string;
};

export type UtilsTestEmailResponse = Message;

export type UtilsHealthCheckResponse = boolean;
